name: password_tracker
description: A new Flutter project.
publish_to: 'none'
version: 1.2.0+23

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  encrypt: ^5.0.1
  crypto: ^3.0.3
  logger: ^2.0.1
  provider: ^6.0.5
  local_auth: ^2.1.6
  file_picker: ^5.3.3
  path_provider: ^2.1.0
  # flutter_share: ^2.0.0
  share_plus: ^7.1.0
  # share_extend: ^2.0.0
  permission_handler: ^10.4.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - icons/icon.png